import type { Metadata } from 'next';
import { Roboto } from 'next/font/google';
import './global.css';
import { Navbar } from '../components/navbar';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

const roboto = Roboto({
  weight: ['400', '500', '700'],
  style: ['normal', 'italic'],
  subsets: ['latin'],
  display: 'swap',
});

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className={roboto.className}>
      <body className="bg-white">
        <Navbar />
        {children}
      </body>
    </html>
  );
}
