name: lint-and-test
on:
  workflow_call:
jobs:
  lint-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Lint
        run: npm run eslint

      - name: Unit tests
        run: npm run test:unit:run
